# Using try-except, how can we recover?
num1 = input('divide: ')
num2 = input('by:     ')

print('you typed in:', num1, num2)

divided = num1 / num2

print(divided)

